FROM docker.io/library/golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN make

FROM registry.fedoraproject.org/fedora:latest

ARG OC_VERSION=latest
ARG TARGETARCH
ARG TESTSSL_VERSION=3.2.2

RUN dnf -y update && \
    dnf install -y binutils file golang podman runc jq skopeo tar lsof wget openssl bash curl && \
    dnf clean all

RUN wget -O "openshift-client-linux-${OC_VERSION}.tar.gz" "https://mirror.openshift.com/pub/openshift-v4/${TARGETARCH}/clients/ocp/${OC_VERSION}/openshift-client-linux.tar.gz" && \
    tar -C /usr/local/bin -xzvf "openshift-client-linux-$OC_VERSION.tar.gz" oc && \
    rm -f "openshift-client-linux-$OC_VERSION.tar.gz"

# Install testssl.sh
RUN curl -L "https://testssl.sh/testssl.sh-${TESTSSL_VERSION}.tar.gz" -o /tmp/testssl.tar.gz && \
    mkdir -p /opt/testssl && \
    tar -xzf /tmp/testssl.tar.gz -C /opt/testssl --strip-components=1 && \
    chmod +x /opt/testssl/testssl.sh && \
    ln -s /opt/testssl/testssl.sh /usr/local/bin/testssl.sh && \
    rm -f /tmp/testssl.tar.gz

COPY --from=builder /app/bin/tls-scanner /usr/local/bin/tls-scanner

ENTRYPOINT ["/usr/local/bin/tls-scanner"]

LABEL com.redhat.component="tls-scanner"
